### ISSUE TITLE
TastytradeError('Subscription channel not opened') raised

### ISSUE THREAD

**Issue by Quenos** [tastyware/tastytrade#101]
**Describe the bug**
In the DXLink streamer subscribing to a symbol raises TastytradeError('Subscription channel not opened')

**How to reproduce**

```
async def get_quotes():
    streamer = await DXLinkStreamer.create(session)
    subs = ['GLD']
    await streamer.subscribe(EventType.QUOTE, subs)
    quotes = []
    async for quote in streamer.listen(EventType.QUOTE):
        print(quote)
        if len(quotes) >= len(subs):
            break
```

** Solved in PR #100

**Comment by Graeme22** [comment]
Can confirm this issue, I had the streamer working yesterday but I must have broken something. Please submit a PR from the master branch with a single commit.
