### ISSUE TITLE
Problems with asyncio + any example of a simple strategy to test in CERT sessions?

### ISSUE THREAD

**Issue by JaphyR** [tastyware/tastytrade#102]
Hei there,
I have several probs in using all the asyncio functions, which is quite frustrating considering how complete this API is (much better than the official SDK!). This API is the best alternative to the official one, so it's a pity not to be able to use it to its full extent

A typical example of what goes wrong (I'm on Python 3.7.3):
    streamer = await DXFeedStreamer.create(session)
              ^
SyntaxError: 'await' outside function

So, it's not clear how/when/where to trigger asyncio , and how the related functions should be called within it.
This is in line with what is mentioned here: https://github.com/tastyware/tastytrade/issues/93.

Also, it would be interesting to have a few simple examples of a complete strategy built on top of this API, e.g. an SMA-driven strat (pulling different modules like session, streamer, quote, order, etc.) to test on the CERT side. For example, how to dump real-time streamer quotes in a df to run algo strats on it and generate buy/sell signals?

Thanks for your great work + Happy to test further,
Cheers/J

**Comment by Graeme22** [comment]
Hello! I'd recommend looking up a tutorial online. asyncio calls must be inside an async function that you call with `asyncio.run()`. If you just want to test, Jupyter notebooks let you make asyncio calls directly.

Take a look at this for an example: https://tastyworks-api.readthedocs.io/en/latest/data-streamer.html

**Comment by Graeme22** [comment]
Specifically, the "Advanced Usage" section shows how to use asyncio.
