### ISSUE TITLE
pulling historical ohlc?

### ISSUE THREAD

**Issue by fritol** [tastyware/tastytrade#108]
Is there any way to pull historical data?
I mean how does their web UI pull chart data?

**Comment by Quenos** [comment]
This can be done with the DXLinkStreamer 

```
subs = ['SPY', 'AAPL']
await streamer.subscribe_candle(subs, '1d', start_date)
candle = await streamer.get_event(EventType.CANDLE)
```

**Comment by autsauce** [comment]
> This can be done with the DXLinkStreamer
> 
> ```
> async with DXLinkStreamer(session) as streamer:
>     subs = ['SPY', 'AAPL']
>     await streamer.subscribe_candle(subs, '1d', start_date)
>     candle = await streamer.get_event(EventType.CANDLE)
> ```

Is this supposed to work with futures contracts as well?

**Comment by Graeme22** [comment]
Yes, you'll need to use dxfeed notation for futures though: https://tastyworks-api.readthedocs.io/en/latest/dxfeed.html
