### ISSUE TITLE
List nested options chain missing requirements error

### ISSUE THREAD

**Issue by mcelia2324** [tastyware/tastytrade#115]
pydantic.error_wrappers.ValidationError: 1 validation error for NestedOptionChain
put-streamer-symbol
  field required (type=value_error.missing)

This was working yesterday but now for any ticker I am receiving the above error, seems put-streamer-symbol is the issue, was this because it used to return "put_streamer_symbol" and now the dashes might be causing an issue?

Can you see if you can replicate?

Thank you

**Comment by mcelia2324** [comment]
I see your _dasherize function is used to handle this case but I am not sure if it is either working properly or if it is something else altogether.

**Comment by Graeme22** [comment]
Hi, can you post the code that's not working for you and the symbol that you're fetching the chain for? Thank!
