### ISSUE TITLE
DXLinkStreamer not working with Python 3.12

### ISSUE THREAD

**Issue by Quenos** [tastyware/tastytrade#135]
**Describe the bug**
In Python 3.12 creating a DXLinkStreamer causes a timeout in async def __aenter__(self):
because self._authenticated will not become True

**How to reproduce**
Python 3.12
streamer = await DXLinkStreamer.create(session)

The exact same code works on Python 3.9

**Comment by Graeme22** [comment]
Weird! Do you know of any changes to asyncio in python 3.12?

**Comment by Quenos** [comment]
I've found one reference of a breaking change in 3.11, but I don't get what they are talking about and if it's even relevant :)\

https://news.ycombinator.com/item?id=33727311

**Comment by Graeme22** [comment]
Hey @Quenos, I finally got around to testing this and for me it's working with no problems with Python 3.12. Could you maybe provide more context? OS, exact Python version, etc.

**Comment by Quenos** [comment]
I'm 3.12.2
But I created a complete new environment and now it works. Don't know what went wrong.

So I close this issue.
