### ISSUE TITLE
Can you provide more examples of SPX (not SPY) Option Chain?

### ISSUE THREAD

**Issue by kowkowhuang** [tastyware/tastytrade#14]
Hello Graeme,

Came across this AMAZING library and interested in more examples / jupyter notes of option chain

For instance,

How can we call SPX to understand 

1. available strikes across the option chain for today (e.g. +/- 25 strikes)
2. For each strike, its put, call
3. each put/call's bid and ask price (Or a midpoint price?)
4. each put/call's delta / in-the-money probability

**Comment by Graeme22** [comment]
Hey! Take a look at the documentation here: https://tastyworks-api.readthedocs.io/en/latest/tastytrade.html#tastytrade.option.get_option_chain

And an example for your question 1:
```python
from tastytrade.session import Session
from tastytrade.option import get_option_chain
from datetime import date

session = Session('user', 'pass')
chain = await get_option_chain(session, 'SPX', date(2023, 5, 19))
print(chain.get_all_strikes())
```

Question 2 I don't understand, each strike has a put and a call.
For question 3, you need to use the DataStreamer:
```python
from tastytrade.streamer import DataStreamer
from tastytrade.dxfeed.event import EventType

streamer = await DataStreamer.create(session)
option = chain.options[10]  # this is a list of all options in the chain

quote = await streamer.stream(EventType.QUOTE, [option.symbol_dxf])
print(quote)
```

If I recall correctly, ITM probability is just a calculation based off of the option greeks, so you could do:
```python
greeks = await streamer.stream(EventType.GREEKS, [option.symbol_dxf])
print(greeks)
```

For more examples, you can look at my CLI: https://github.com/tastyware/tastytrade-cli

**Comment by Graeme22** [comment]
In general, the documentation is a bit lacking, but I'm currently working on an overhaul of the whole API, so hopefully there will be better documentation soon.
