### ISSUE TITLE
Feature request: Non-Blocking DXLinkStreamer.get_event

### ISSUE THREAD

**Issue by Quenos** [tastyware/tastytrade#148]
**Describe the feature**
Use case:

In the current implementation of the streamer it's necessary to stop and start the streamer, when subscribing or unsubscribing symbols. This is necessary because - especially when the exchanges are closed - the stream can be waiting for new events to arrive. As long as it's waiting no new symbols can be added or removed.

As stopping and then starting the DXLinkStreamer again is expensive is expensive, there is a use case for a non-blocking version of DXLinkStreamer.get_event.

**Comment by Graeme22** [comment]
Thanks!
