### ISSUE TITLE
get_equity() returns wrong info

### ISSUE THREAD

**Issue by Conceptron** [tastyware/tastytrade#152]
`instruments.Equity.get_equity(session, 'NVDL')` returns info about Novadel pharma (a stock that was delisted back in 2017) instead of "GraniteShares 2x Long NVDA Daily ETF"

The tastytrade website seems to use a different API "https://vast.tastyworks.com/symbols/search/NVDL" to get symbol information

**Comment by Graeme22** [comment]
Interesting! This seems like a problem with the API, not the SDK, so I'd recommend you write Tasty support directly.
