### ISSUE TITLE
Subscribing to candles on 2 different timeframes (or intervals)

### ISSUE THREAD

**Issue by syserr** [tastyware/tastytrade#157]
Hi @Graeme22 thank you for this great project.

I'm struggling to learn asyncio well enough to do some more advanced things.  I've read the advanced section here https://tastyworks-api.readthedocs.io/en/latest/data-streamer.html#advanced-usage.  I've also read through the tests/test_streamer.py.

My question is how would you go about getting candles on 2 different timeframes (or intervals).  At first I thought 2 different streams, then I decided 1 stream with 2 subscriptions was the right way.

```python
async def get_candles():
    session = as_tasty_session_token()
    dt = datetime(2024,7,12,7,0,0)
    async with DXLinkStreamer(session) as streamer:
        await streamer.subscribe_candle(['SPY'], '15m', dt)
        await streamer.subscribe_candle(['QQQ'], '30m', dt)
        async for c in streamer.listen(EventType.CANDLE):
            print(c)

if __name__ == "__main__":
    asyncio.run(get_candles())
```

That code seems to get wedged on the "async for" so I'm guessing multiple .subscribe_candle() on one stream isn't supported?

I'm just wondering if there is a way to do this within the same process?  If multiple streams is the answer, how many streams can you have without trouble?  And is there a best practice for having 2 streams running in one process?

Thanks you!

**Comment by Graeme22** [comment]
Hey! Thanks for opening this issue. This is actually a bug in the SDK, the code you posted should work correctly! I fixed it and it will work in the next release.

**Comment by Graeme22** [comment]
Can you confirm this is fixed for you in v7.9?

**Comment by syserr** [comment]
@Graeme22, I tested v7.9 and it works exactly as it should -- both timeframes are coming through at the same time.  Thank you!

**Comment by Graeme22** [comment]
Great!
