### ISSUE TITLE
Candle Stream Connection Failure

### ISSUE THREAD

**Issue by Vscheidell** [tastyware/tastytrade#161]
Hello all,

I noticed yesterday my script stop receiveing data around 10:13.  When I went to the logs, these were the latest entries. Is it safe to assume that my machine simply lost internet connection for a minute which is why the keepalive pings failed and eventually ended the connection?

DEBUG | 2024-08-08 10:13:26,508 | func: subscribe | line: 441 | sending subscription: {'type': 'FEED_SUBSCRIPTION', 'channel': 1, 'add': [{'symbol': 'SPY', 'type': <EventType.CANDLE: 'Candle'>}, {'symbol': 'QQQ', 'type': <EventType.CANDLE: 'Candle'>}, {'symbol': 'IWM', 'type': <EventType.CANDLE: 'Candle'>}, {'symbol': 'AAPL', 'type': <EventType.CANDLE: 'Candle'>}]} | MainThread: 17344
DEBUG | 2024-08-08 10:13:26,508 | func: write_frame_sync | line: 1174 | > TEXT '{"type": "FEED_SUBSCRIPTION", "channel": 1, "ad...I", "type": "Candle"}]}' [201 bytes] | MainThread: 17344
DEBUG | 2024-08-08 10:13:42,324 | func: keepalive_ping | line: 1261 | % sending keepalive ping | MainThread: 17344
DEBUG | 2024-08-08 10:13:42,324 | func: write_frame_sync | line: 1174 | > PING 10 45 97 98 [binary, 4 bytes] | MainThread: 17344
DEBUG | 2024-08-08 10:13:46,871 | func: _heartbeat | line: 415 | sending keepalive message: {'type': 'KEEPALIVE', 'channel': 0} | MainThread: 17344
DEBUG | 2024-08-08 10:13:46,871 | func: write_frame_sync | line: 1174 | > TEXT '{"type": "KEEPALIVE", "channel": 0}' [35 bytes] | MainThread: 17344
DEBUG | 2024-08-08 10:14:02,337 | func: keepalive_ping | line: 1271 | ! timed out waiting for keepalive pong | MainThread: 17344
DEBUG | 2024-08-08 10:14:02,337 | func: fail_connection | line: 1409 | ! failing connection with code 1011 | MainThread: 17344
DEBUG | 2024-08-08 10:14:02,337 | func: fail_connection | line: 1433 | = connection is CLOSING | MainThread: 17344
DEBUG | 2024-08-08 10:14:02,337 | func: write_frame_sync | line: 1174 | > CLOSE 1011 (unexpected error) keepalive ping timeout [24 bytes] | MainThread: 17344
DEBUG | 2024-08-08 10:14:03,991 | func: connection_lost | line: 1494 | = connection is CLOSED | MainThread: 17344
DEBUG | 2024-08-08 10:14:16,888 | func: _heartbeat | line: 415 | sending keepalive message: {'type': 'KEEPALIVE', 'channel': 0} | MainThread: 17344

**Comment by Graeme22** [comment]
It does look like that, but not quite for sure... It is something you've only experienced once? If you can reproduce it then it's likely a bug.

**Comment by Vscheidell** [comment]
I have experienced it twice, both times last week.
I will monitor/try to reproduce and provide any updates.

**Comment by Graeme22** [comment]
Hi @Vscheidell, v9.4 contains some utilities to handle connection failures by automatically reconnecting and optionally running a callback upon reconnection. Check it out, should make your app more resilient to these kinds of failures.
