### ISSUE TITLE
TypeError when plotting account performance using start-time parameter

### ISSUE THREAD

**Issue by agu2a** [tastyware/tastytrade#172]
When I plot the performance of my account using time_back as parameter I can see the chart successfully.

HOWEVER, when I use a specific date instead is gives me this type error...
TypeError: string indices must be integers

I use the following code:
`from_date = datetime(2024, 8, 28, 0, 0, 0)`
`nl = account.get_net_liquidating_value_history(session, start_time=from_date )`

**Comment by Graeme22** [comment]
Hey, thanks for opening this!

I did some digging and it looks like there's something wrong on with the Tastytrade API, so there's nothing the SDK can do to resolve this at this time, unfortunately! Maybe you could reach out to the support team and tell them that the endpoint is not working as expected.

**Comment by agu2a** [comment]
Hey @Graeme22, I think this issue can be closed.
I reached out to the API team at Tasty and they didn't have any clear answers. I think there's something else not properly set on their end. Thanks

**Comment by Graeme22** [comment]
Thanks for looking into it!
