### ISSUE TITLE
Can't place an order

### ISSUE THREAD

**Issue by ccjoeg** [tastyware/tastytrade#174]
I can't believe this is an API bug but I haven't been able to get it to work. Please take a look and tell me what I am doing wrong.

Thanks
Joe

import json
from datetime import datetime
from decimal import Decimal
from tastytrade import Account
from tastytrade.instruments import Equity
from tastytrade.order import NewOrder, OrderAction, OrderTimeInForce, OrderType

def buy_shares(session, account):
    account = Account.get_account(session, account.account_number)
    symbol = Equity.get_equity(session, 'USO')
    leg = symbol.build_leg(Decimal('1'), OrderAction.BUY_TO_OPEN)  # buy to open 1 shares

    order = NewOrder(
        time_in_force=OrderTimeInForce.DAY,
        order_type=OrderType.LIMIT,
        legs=[leg],  # you can have multiple legs in an order
        price=Decimal('-10')  # limit price, $10/share debit for a total value of $50
    )
    print(f"\norder: {order}\n")
    try:
        response = account.place_order(session, order, dry_run=True)  # a test order
        print(f"Order placed successfully: {response}")
    except Exception as e:
        print(f"An error occurred: {e}")
        if hasattr(e, 'response'):
            print(f"API response: {e.response.text}")

order: time_in_force=<OrderTimeInForce.DAY: 'Day'> order_type=<OrderType.LIMIT: 'Limit'> source='tastyware/tastytrade:v9.0' legs=[Leg(instrument_type=<InstrumentType.EQUITY: 'Equity'>, symbol='USO', action=<OrderAction.BUY_TO_OPEN: 'Buy to Open'>, quantity=Decimal('1'), remaining_quantity=None, fills=None)] gtc_date=None stop_trigger=None price=Decimal('-10') value=None partition_key=None preflight_id=None rules=None price_effect=<PriceEffect.DEBIT: 'Debit'> value_effect=None

An error occurred: 1 validation error for PlacedOrderResponse
order.id
  Field required [type=missing, input_value={'account-number': '5WV99...': 'USO', 'fills': []}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing

$ pip show tastytrade
Name: tastytrade
Version: 9.0
Summary: An unofficial, sync/async SDK for Tastytrade!
Home-page: 
Author: 
Author-email: Graeme Holliday <graeme.holliday@pm.me>
License: MIT License
.
.
.
Location: 
Requires: httpx, pandas-market-calendars, pydantic, websockets

**Comment by Graeme22** [comment]
Hi, I was aware of this error but hadn't gotten around to fixing it. It only applies to orders with `dry_run=True`, if you need that functionality for now you can downgrade to v8.5. Sorry about that!

**Comment by ccjoeg** [comment]
Hi,

That fixed it. This change will make it work with dry-run=True:

--- tastytrade-master/tastytrade/order.py 2024-10-29 11:24:41.000000000
-0600
+++ trader/tastytrade/order.py 2024-11-04 19:21:58.238780058 -0700
@@ -281,7 +281,7 @@
     """

     account_number: str
-    id: int
+    id: Optional[int] = None
     time_in_force: OrderTimeInForce
     order_type: OrderType
     underlying_symbol: str

Thanks,
Joe
