### ISSUE TITLE
SPX quotes not streaming 

### ISSUE THREAD

**Issue by nkmrao** [tastyware/tastytrade#175]
When I try to stream quotes, I am able to stream AAPL and SPY but not SPX. Is it just in my case? If so, what am I doing wrong? 

```
from tastytrade import Session
from tastytrade import DXLinkStreamer
from tastytrade.dxfeed import Quote
from threading import Thread
import asyncio

from config import USERNAME_SANDBOX, PASSWORD_SANDBOX

subs_list = ['AAPL', 'SPY', 'SPX']

session = Session(USERNAME_SANDBOX, PASSWORD_SANDBOX, is_test=True)

async def main(session):
    async with DXLinkStreamer(session) as streamer:
        await streamer.subscribe(Quote, subs_list)
        
        n = 0
        while n < 20:
            quote = await streamer.get_event(Quote)
            print(quote)
            n += 1
        
Thread(target=asyncio.run, args=(main(session),)).start() 
```

**Comment by nkmrao** [comment]
Oh ok. The documentation may need updating then because there are examples of Quotes being received for SPX as well. 
I am not having luck with the Trade event as well.  I receive SPX options prices but not the underlying index price. 
Any other solution? There must be an easy way to retrieve/stream index prices.

**Comment by Graeme22** [comment]
Good point about the docs, I'll have to fix that!
This code is working fine for me:

```python
async with DXLinkStreamer(session) as streamer:
    await streamer.subscribe(Trade, ['SPX'])
    t = await streamer.get_event(Trade)
    print(t)
```

**Comment by Graeme22** [comment]
Looking at your code again, you'll want to use a real session instead of the sandbox session, which has limited streamer functionality.

**Comment by nkmrao** [comment]
It was indeed because of the limited functionality of the sandbox session. 
I am able to stream quotes for SPX in the live account as well.  Thanks.

**Comment by DustinJSilk** [comment]
Is it possible to stream Candle data for SPX? i can see it being used in the Tastytrade web platform but Im not getting any response from the API. Im using the DXLink Go SDK, and Ive also tried the TypeScript SDK to no avail. 

```TypeScript
import {  DXLinkWebSocketClient,  DXLinkFeed,  FeedContract,  FeedDataFormat} from "@dxfeed/dxlink-api";

const client = new DXLinkWebSocketClient();

client.connect("wss://tasty-openapi-ws.dxfeed.com/realtime");
client.setAuthToken("...");

const feed = new DXLinkFeed(client, FeedContract.AUTO);

feed.configure({  acceptAggregationPeriod: 1,  acceptDataFormat: FeedDataFormat.COMPACT,  acceptEventFields: {    Candle: ["eventSymbol", "open", "close", "high", "low", "volume"],  },});

feed.addSubscriptions({
  type: "Candle",
  symbol: "SPX",
});

feed.addEventListener((events) => {
  console.log(events);
});

setInterval(() => {}, 1 << 30);
```

**Comment by Graeme22** [comment]
> Is it possible to stream Candle data for SPX? i can see it being used in the Tastytrade web platform but Im not getting any response from the API. Im using the DXLink Go SDK, and Ive also tried the TypeScript SDK to no avail.

Hi, it is indeed! Check out the docs: https://tastyworks-api.readthedocs.io/en/latest/

**Comment by DustinJSilk** [comment]
I’ve emailed tastytrade api support and they’ve mentioned that SPX will be available in the coming weeks.

**Comment by ccjoeg** [comment]
Hi,

I'm confused as to the problem. Is it just not working in the sandbox? I am
streaming SPX live with no problem at a 1 second rate.

0:08:50.0 quote_dict_len5:
SPY bid: 603.88 ask: 603.9
SPX bid: 6048.59 ask: 6051.42

10:08:51.2 quote_dict_len5:
SPY bid: 603.88 ask: 603.9
SPX bid: 6048.43 ask: 6051.24

10:08:52.4 quote_dict_len5:
SPY bid: 603.88 ask: 603.9
SPX bid: 6048.44 ask: 6051.23

10:08:53.6 quote_dict_len5:
SPY bid: 603.89 ask: 603.91
SPX bid: 6048.54 ask: 6051.3

I can share code if it will help someone.

Thanks,
Joe
