### ISSUE TITLE
How to specify advanced-instructions when placing orders

### ISSUE THREAD

**Issue by salamad** [tastyware/tastytrade#178]
I would like to specify `advanced-instructions`, particularly `strict-position-effect-validation: true` when placing orders. However, I could not find anywhere in the documentation or the source code how I can include this when calling NewOrder.

**Comment by Graeme22** [comment]
I'm afraid you may be on your own on that one! You can try experimenting with the fields to see what happens, but I have no idea how it works to be honest. I'll leave this issue open in case anyone else has already done this and has some insights.

**Comment by agu2a** [comment]
I was about to ask about this as well. I tested with dry-run True to avoid opening a position and the PlaceOrder Response under warnings say the following:
`code='closing_with_no_position', message='You cannot route a closing order without an existing position to close. This order will be updated to a buy to open order when routed.', preflight_id=None)`
I'm thinking of embedding the `advanced-instructions` into the JSON attributes of the order object somehow. I'm gonna play around with it a bit to see if it works

**Comment by Graeme22** [comment]
> ** Temporary FIX **
> This may not be ideal but does the trick, please test first and make sure you do so with `dry_run=True`
> Go to the **order.py** file and find the NewOrder class around the 214~224 line.  At the end of that class, right after the rules variable paste this line `advanced_instructions: str = {"strict-position-effect-validation":True}`
> 
> Let me know what message you receive. On my end it was successful

Interesting, could you submit a PR adding that as an optional field?

**Comment by agu2a** [comment]
Will do !

**Comment by agu2a** [comment]
Hey Graeme,
I don't really know how to open that Pull Request. If you can give me some
guidance on it that would be great.

On a separate note, do you know how to implement the heartbeat feature to
keep the session alive?

Thx
_______________________
*Andres Usma*

**Comment by Graeme22** [comment]
Btw, could someone explain what strict position effect validation does/means? Not immediately clear to me

**Comment by agu2a** [comment]
If you put a closing order but for whatever reason the position you want to close is no longer opened then the API will turn that closing order into an order to open. 

By adding that variable the API will not simply discard the closing order.
