### ISSUE TITLE
Thank you for the streamer.py module (market data is working now)

### ISSUE THREAD

**Issue by pressplay21** [tastyware/tastytrade#18]
I've been trying to figure out how to get dxfeed working for a few days now. I emailed tastytrade and dxfeed folks but no response. 
Finally I found your python modules.

from tastytrade.session import Session
from tastytrade.streamer import DataStreamer, EventType, AuthExtension

API_URL = 'https://api.cert.tastyworks.com' #Maybe we can enable sandbox parameter via Session and API_URL should change.
session = Session(TT_USER,TT_PASS)
streamer = await DataStreamer.create(session)
subs_list = ['SPX']
trade = await streamer.stream(EventType.TRADE, subs_list)
trade[0].price

**Comment by peter-oroszvari** [comment]
I spent cca. 2 weeks to understand the concept behind cometd and dxfeed and make it work with websockets. I feel your pain. :D I open an issue to your suggestion regarding the sandbox parameter.
