### ISSUE TITLE
AlertStreamer wont initialize: BaseEventLoop.create_connection() got an unexpected keyword argument 'extra_headers'

### ISSUE THREAD

**Issue by jackroc97** [tastyware/tastytrade#182]
**Describe the bug**
Trying to use the AlertStreamer in the manner described in the docstring results in `TypeError:  BaseEventLoop.create_connection() got an unexpected keyword argument 'extra_headers'`.

**How to reproduce**
```python

import asyncio

from tastytrade import Account, AlertStreamer, Session
from tastytrade.order import PlacedOrder


async def main():

    session = Session("prod_user", "prod_pass")
    
    async with AlertStreamer(session) as streamer:    # <--- This line causes the error
        accounts = Account.get_accounts(session)

        # updates to balances, orders, and positions
        await streamer.subscribe_accounts(accounts)
        # changes in public watchlists
        await streamer.subscribe_public_watchlists()
        # quote alerts configured by the user
        await streamer.subscribe_quote_alerts()

        async for order in streamer.listen(PlacedOrder):
            print(order)
            

asyncio.run(main())
```

I have done some minimal debugging and found that the unexpected kwarg `extra_headers` is set on the websocket connection in lines 224-226 of streamer.py.

**Comment by Graeme22** [comment]
This will be fixed in the next release, for now you can downgrade `websockets` to 13.1. They released breaking changes in 14.1 that are imported under the same names, which causes this error.
