### ISSUE TITLE
event_flags signaling broken with Rel. 9.3 due to missing REMOVE_EVENT candles

### ISSUE THREAD

**Issue by JBlohm** [tastyware/tastytrade#183]
**Bug description**
With Rel. 9.3 the open / high / low / close fields have lost their optionality.

This leads to candles with "none" as value for any of these fields to not be received any more.
Problem now: The event_flags attached to these candles can now also not be evaluated anymore, which breaks any code that relies on theses flags to determine the start and end of a snapshot, to display the data when the snapshot data is completely received. (SNAPSHOT_BEGIN still works, but SNAPSHOT_END cannot be received anymore if is attached to a REMOVE_EVENT candle, which is often the case. REMOVE_EVENT candles (generally / often) have their values set to None.

**How to reproduce**
Works with 9.2:

```
        await streamer.subscribe_candle(symbols=subs_list, interval="1d", start_time = epoch)
        df = pd.DataFrame()
        last_candle = False
        snap_count = 0

        while not last_candle:
            try:
                candle = await asyncio.wait_for(streamer.get_event(Candle), timeout=1.0)
                #print(candle)

                if (candle.eventFlags & SNAPSHOT_BEGIN) != 0:
                    snap_count += 1

                if (candle.eventFlags & SNAPSHOT_END) != 0:
                    snap_count -= 1
                    if snap_count == 0:
                        last_candle = True

                if (candle.eventFlags & REMOVE_EVENT) == 0: # if this is not a remove event, process the candle
                    df_new = candle_to_dataframe(candle)
                    df = pd.concat([df, df_new], axis=0, ignore_index=False)

                print(snap_count)

            except TimeoutError:
                print("DEBUG: get_event(Candle) : timeout")
```

Does not work with 9.3 because SNAPSHOT_END / REMOVE_EVENT cannot be received.

```
        await streamer.subscribe_candle(symbols=subs_list, interval="1d", start_time = epoch)
        df = pd.DataFrame()
        last_candle = False
        snap_count = 0

        while not last_candle:
            try:
                candle = await asyncio.wait_for(streamer.get_event(Candle), timeout=1.0)
                #print(candle)

                if (candle.event_flags & SNAPSHOT_BEGIN) != 0:
                    snap_count += 1

                if (candle.event_flags & SNAPSHOT_END) != 0:
                    snap_count -= 1
                    if snap_count == 0:
                        last_candle = True

                if (candle.event_flags & REMOVE_EVENT) == 0: # if this is not a remove event, process the candle
                    df_new = candle_to_dataframe(candle)
                    df = pd.concat([df, df_new], axis=0, ignore_index=False)

                print(snap_count)

            except TimeoutError:
                print("DEBUG: get_event(Candle) : timeout")
```

**Comment by JBlohm** [comment]
```
TX_PENDING = 0x1
REMOVE_EVENT = 0x2
SNAPSHOT_BEGIN = 0x4
SNAPSHOT_END = 0x8
SNAPSHOT_SNIP = 0x10
SNAPSHOT_MODE = 0x40
```

**Comment by Graeme22** [comment]
Interesting. I think this is the desired behavior for the majority of users, so I don't want to change that. However, I could look into an option that would enable this functionality if desired. Potentially we could:
- Raise an exception with the code as metadata
- Add a handler function that the streamer would use when parsing events, so the functionality could be customized

Thoughts?

**Comment by Graeme22** [comment]
> ```
> TX_PENDING = 0x1
> REMOVE_EVENT = 0x2
> SNAPSHOT_BEGIN = 0x4
> SNAPSHOT_END = 0x8
> SNAPSHOT_SNIP = 0x10
> SNAPSHOT_MODE = 0x40
> ```

Also, these are helpful, I'll have to add them to the SDK!

**Comment by JBlohm** [comment]
I thought I provide us with a pointer to the original documentation from DXFeed to help us with the discussion, because I had quite a hard time to actually find it. [https://docs.dxfeed.com/dxfeed/api/com/dxfeed/event/IndexedEvent.html?_ga=2.203071763.304999132.1733505089-692842126.1733505089](url)

Here we can read about the original intention of the data feed supplier on how to use the information contained in the event_flags. When I looked through your code, I found you seem not to use the information provided by the event flags yet.
But the flags are really useful to control the program flow for example when collecting candle data and only display then when all (snapshot end) data is received, to then continue changing the most recent candle in the chart until it switches to the next timeframe (every 5m, for example). 

Another intention of the data feed provider seems to be able to revoke defective data from the stream.
(REMOVE_EVENT) This can prove very useful when storing data in a temporary database for fast access.
Loosing this functionality may lead to false data to sit in the database for some longer time.

So, checking the event flags of each candle/quote etc. before processing it in an application seems to be a good choice to me.

I get the idea, you want to make sure you only provide "valid" candles/quotes from streamer.get_event(Candle), so people do not need to think about the data when collecting and displaying it. I understand that, but actually I think we will lose information that way.

Maybe you could agree to a change like adding a optional binary flag to the function like this: streamer.get_event(Candle, raw_mode=True) to switch between the original behavior (candles with "None" values and REMOVE_EVENT candles are received) and the new behavior as your default setting. (default: raw_mode=False)

**Maybe that can be the deal?**

P.S. I can upload a small application already fully utilizing the eventFlags (Still 9.2 naming style, for reason see above) to control the flow of the data in the program, using the flags DXFeed provides. The application was built be me to demonstrate the use of async use of tkinter, mplfinance and your tastytrade lib all in one program. (So there are many things happening at the "same time" in the program)

**Comment by Graeme22** [comment]
Point taken! I think in #185 I figured out a way to handle it that should work for everybody. I also added utilities for computing the event flags so you don't need to use bitwise math in your code (https://tastyworks-api.readthedocs.io/en/latest/dxfeed.html#module-tastytrade.dxfeed.candle) Cheers!
