### ISSUE TITLE
Issue with opening order in last 30 min

### ISSUE THREAD

**Issue by Vscheidell** [tastyware/tastytrade#188]
Currently I am dry running placing orders and when placing orders throughout the day, everything is working fine. However, within the last 30 min of the day the order response appears to be truncated and the numbers for change in margin requirement and change in buying power are way off. 

**How to reproduce**
Code i am using:

    symbol = Option.get_option(session, occ_string_21_to_open)

    leg = symbol.build_leg(Decimal(quantity), OrderAction.BUY_TO_OPEN)

    order = NewOrder(
        time_in_force=OrderTimeInForce.DAY, 
        order_type=OrderType.MARKET, 
        legs=[leg],  
        price_effect=PriceEffect.DEBIT
    )

    # Place order
    response = account.place_order(session, order, dry_run=dry_run) 
    logging.debug(f"Response to opening order: [{response}]")

Here is the response I receive:

DEBUG | 2024-12-17 15:47:50,160 | func: open_order | line: 1172 | Response to opening order: [buying_power_effect=BuyingPowerEffect(change_in_margin_requirement=Decimal('17987.76'), change_in_margin_requirement_effect=<PriceEffect.DEBIT: 'Debit'>, change_in_buying_power=Decimal('XXXXX'), change_in_buying_power_effect=<PriceEffect.DEBIT: 'Debit'>, current_buying_power=Decimal('XXXXXX'), current_buying_power_effect=<PriceEffect.CREDIT: 'Credit'>, new_buying_power=Decimal('XXXXXX'), new_buying_power_effect=<PriceEffect.DEBIT: 'Debit'>, isolated_order_margin_requirement=Decimal('0.0'), isolated_order_margin_requirement_effect=<PriceEffect.NONE: 'None'>, is_spread=False, impact=Decimal('XXXXX'), effect=<PriceEffect.DEBIT: 'Debit'>) fee_calculation=None order=None complex_order=None warnings=None errors=None] | MainThread: 7912

You can see the response is truncated and the change in margin requirement is through the roof, as is the buying power variables which if have redacted for privacy (i think?).
I use the same code earlier in the day (which returns a full response) and the last 30 min (which returns the above truncated response)
The occ_string_21_to_open symbol I use earlier in the day and the one at the end is the exact same 'SPY   241217P00605000'

It appears as if the only difference is that this code runs at the last 30 min of the day. Is this an artifact of dry running? will I have this issue with live trading?

**Comment by Graeme22** [comment]
Hi @Vscheidell! So the responses from the API don't have anything to do with the SDK, which simply formats them and passes them along. If you continue to have this problem, you should reach out to the API team at api.support@tastytrade.com.
