### ISSUE TITLE
Performance to get candles

### ISSUE THREAD

**Issue by pingzh** [tastyware/tastytrade#45]
Hi @Graeme22 wondering if you have tested the performance of `oneshot_candle`?, i noticed that it could take like `10 seconds` to get the SPX 1-minute candle for just a day.

**Comment by Graeme22** [comment]
Hey! I noticed the same thing. I did some tests and profiling and came to some conclusions:

- this behavior only applies the *first* time you call the `oneshot_candle` function, not subsequent calls.
- the same behavior applies to the `oneshot` and `listen` functions
- the waiting is occurring at line 251 of streamer.py: `raw_message = await self._websocket.recv()`
- if you wait for 10 seconds before executing the first function, it runs almost instantly

Conclusion: once the handshake completes, although setup is completed locally, remotely there is still some kind of setup process that hasn't happened that takes about 8-9 seconds, and afterwards you're good to go. Unfortunately, there's no way to know when that process concludes remotely, as there's no kind of confirmation message sent. So there's no way to solve this problem really, I could insert a wait into the `create` function, but that's no guarantee and it makes more sense to just await the results anyways.

Solutions: just use await, unfortunately there's nothing else that can be done. The good news is that after the setup time at the beginning, it's no longer a problem and everything executes relatively quickly.

(Side note: this is probably why the Tastytrade clients always take so long to start up hahaha)

**Comment by Graeme22** [comment]
I suppose one hacky solution would be to put a oneshot into your initialization code:

```python
async def safe_create(session: Session) -> DataStreamer:
    streamer = await DataStreamer.create(session)
    _ = await streamer.oneshot(EventType.QUOTE, ['SPY'])

    return streamer
```

**Comment by Graeme22** [comment]
> I suppose one hacky solution would be to put a oneshot into your initialization code:
> 
> ```python
> async def safe_create(session: Session) -> DataStreamer:
>     streamer = await DataStreamer.create(session)
>     _ = await streamer.oneshot(EventType.QUOTE, ['SPY'])
> 
>     return streamer
> ```

Something like this could go into the `create` function, maybe that would be wise, although total setup time would be around 14 seconds for the streamer...

**Comment by Graeme22** [comment]
I went ahead and fixed this by inserting a `oneshot` into the `create` function. Setup takes longer now but once you have the streamer object it's guaranteed to be initialized.

**Comment by pingzh** [comment]
@Graeme22 i am wondering if you have support fo `sync` function instead of await/async?

**Comment by Graeme22** [comment]
Not sure what your use case is, but the streamer is async to allow for concurrency; for example, it'd be common to have one task listening for quotes and another handling subscriptions. Of course, if you don't need those features you don't have to use them; just do everything in a single task.
