### ISSUE TITLE
get_cryptocurrency() can't find BTC/USD?

### ISSUE THREAD

**Issue by rifling-spread-0k** [tastyware/tastytrade#52]
Hello,

I'm trying to get a crypto object for the "BTC/USD" symbol with:
crypto = Cryptocurrency.get_cryptocurrency(session, 'BTC/USD')

but the tastytrade API always returns: 
"tastytrade.utils.TastytradeError: record_not_found: Couldn't find Cryptocurrency. "

I'm new to this API, so please let me know if I'm doing something wrong. Thanks!

**Comment by Graeme22** [comment]
My guess is the account you're using doesn't have cryptocurrency enabled. Unfortunately the API doesn't work for non-crypto-enabled accounts (just quotes I think) and the test (certification) account doesn't either.

**Comment by Graeme22** [comment]
Can you try with a non-test, crypto-enabled account?

**Comment by rifling-spread-0k** [comment]
You are correct, it does *not* work in the test environment, but it works with my production account/environment! 

Thank you for your work on the SDK. It's very exciting!  More questions on the way..
