### ISSUE TITLE
get_balance_snapshots() fails with production account?

### ISSUE THREAD

**Issue by rifling-spread-0k** [tastyware/tastytrade#53]
This works with my test account in the test environment, but fails when I'm signed in to my production account:

accountBuyingPowerSnapshotList=account.get_balance_snapshots(session)
 
Error Message:
  accountBuyingPowerSnapshotList=account.get_balance_snapshots(session)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/tastytrade/account.py", line 506, in get_balance_snapshots
    return [AccountBalanceSnapshot(**entry) for entry in data]
  File "/home/ec2-user/.local/lib/python3.9/site-packages/tastytrade/account.py", line 506, in <listcomp>
    return [AccountBalanceSnapshot(**entry) for entry in data]
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 9 validation errors for AccountBalanceSnapshot
long-cryptocurrency-value
  field required (type=value_error.missing)
short-cryptocurrency-value
  field required (type=value_error.missing)
cryptocurrency-margin-requirement
  field required (type=value_error.missing)
unsettled-cryptocurrency-fiat-amount
  field required (type=value_error.missing)
unsettled-cryptocurrency-fiat-effect
  field required (type=value_error.missing)
closed-loop-available-balance
  field required (type=value_error.missing)
equity-offering-margin-requirement
  field required (type=value_error.missing)
long-bond-value
  field required (type=value_error.missing)
bond-margin-requirement
  field required (type=value_error.missing)

**Comment by Graeme22** [comment]
Nice catch! Looks like these are `Optional` values and not required ones. Would you be able submit a PR to update the `AccountBalanceSnapshot` class to make those fields optional?

**Comment by rifling-spread-0k** [comment]
I've got a diff here locally. Will test it and circle back next week. 

<img width="873" alt="Screenshot 2023-06-11 at 4 18 45 PM" src="https://github.com/tastyware/tastytrade/assets/135941120/4b699b90-3c4d-467b-b3dc-dbb62ff0b935">

**Comment by rifling-spread-0k** [comment]
This will be my first PR ever, so bear with me :-)

**Comment by Graeme22** [comment]
It looks like you modified `AccountBalance` instead of `AccountBalanceSnapshot`, did you test the fix with your certification account?

**Comment by Graeme22** [comment]
Hi @rifling-spread-0k , I can't reproduce this issue--would you be willing to check if this applies to `AccountBalance` as well? E.g.

```python
session = Session("user", "pass")
accounts = Account.get_accounts(session)
accounts[0].get_balances(session)
```
