### ISSUE TITLE
Historical Greeks data

### ISSUE THREAD

**Issue by roboluc** [tastyware/tastytrade#59]
There is currently an endpoint for historical candle data. I looked at the dxFeed API and TimeSeriesEvent are available for Candle, DailyCandle, Greeks, TheoPrice, TimeAndSale and Underlying [https://docs.dxfeed.com/dxfeed/api/com/dxfeed/event/TimeSeriesEvent.html](https://docs.dxfeed.com/dxfeed/api/com/dxfeed/event/TimeSeriesEvent.html). What would be the best way to implement this?

**Comment by Graeme22** [comment]
We already have candles implemented for Quotes. As for the others, we'd have to check and see if they're supported for Tastytrade customers and go from there.

**Comment by Graeme22** [comment]
Would you be willing to test if you can use the streamer to subscribe to one or more of those things?

**Comment by roboluc** [comment]
I can only subscribe to historical TimeAndSale. I haven't figured out how to subscribe to historical Greeks data or the others.

**Comment by Graeme22** [comment]
Can you share the TimeAndSale subscription and JSON response?

**Comment by roboluc** [comment]
Subscription:
```python
async def subscribe_timeandsale(self, ticker: str, start_time: datetime) -> None:

    id = await self._next_id()
    message = {
        'id': id,
        'channel': Channel.SUBSCRIPTION,
        'data': {
            'addTimeSeries': {
                'TimeAndSale': [{
                    'eventSymbol': f'{ticker}',
                    'fromTime': int(start_time.timestamp() * 1000)
                }]
            }
        },
        'clientId': self.client_id
    }
    logger.debug('sending subscription: %s', message)
    await self._websocket.send(json.dumps([message]))
```
JSON response:
```
{'data': ['TimeAndSale', ['.SPY230703C444', 0, 0, 7250571447855255195, 1688155217064, 0, 36507, 'E', 0.66, 41.0, 0.65, 0.66, 'I', '\x00', 'BUY', False, False, True, 'NEW', None, None]], 'channel': '/service/timeSeriesData'}
```

**Comment by Graeme22** [comment]
Thanks for this, this would be a great feature to have. I'll take a look at some of the other dxfeed types when I get the chance.

**Comment by Graeme22** [comment]
@roboluc would you like to create a PR adding this?

**Comment by Graeme22** [comment]
I finally figured this out! Managed to get historical greeks data, and also found out there's a REST API that can be used apart from the streamer! Lots of new features incoming :)

**Comment by Graeme22** [comment]
I mispoke, there's no historical greeks data; rather, I found historical prices for options. Which is also useful I guess. The REST API part is true haha

**Comment by Graeme22** [comment]
https://tools.dxfeed.com/dxprice/index.jsp?symbol=SPLG&date=20220701&time=12%3A00

This tool appears to work but I think it's actually calculating the greeks on the fly... Hard to know because there's no source code provided.

**Comment by roboluc** [comment]
Do you mean the historical option candle data? You can already get that with: 
```python
streamer.subscribe_candle('.SPY230614C438', datetime(2023, 6, 10, 0, 0, 0), '1m')
```
But it only has 3 months of data. [https://tools.dxfeed.com/dxprice/index.jsp?symbol=SPLG&date=20220701&time=12%3A00](https://tools.dxfeed.com/dxprice/index.jsp?symbol=SPLG&date=20220701&time=12%3A00) I think this is calculating the greeks itself because the historical price data is available. The REST API would be nice to have besides the streamer.

**Comment by Graeme22** [comment]
> But it only has 3 months of data.
Are you sure? I think I was able to get more... Did you use a certification account?

 > I think this is calculating the greeks itself because the historical price data is available.
Yeah, also it says "calculating..." hahaha

> The REST API would be nice to have besides the streamer.
For sure, there's a lot of use cases where you just want the data one time

**Comment by roboluc** [comment]
For 1 minute options candle data, I could only go back to a maximum of 3 months. If you change the interval to 1 hour you can go back further. It's the same with a certification account.

**Comment by Graeme22** [comment]
That's probably just a limitation of the dxfeed API then, you may need to pay more for a premium subscription, especially if you're looking to do super precise backtesting.

**Comment by Graeme22** [comment]
I'm going to close this because there doesn't appear to be any feasible way to implement historical greeks data.
