### ISSUE TITLE
AccountBalance throws exception on missing data

### ISSUE THREAD

**Issue by jimbkim** [tastyware/tastytrade#60]
in the account.py file,  I updated the data class as follows because the API doesn't return these keys anymore, although it's still int he docs.

    apex_starting_day_margin_equity: Decimal = Field(default = None)
    buying_power_adjustment: Decimal = Field(default = None)
    buying_power_adjustment_effect: PriceEffect = Field(default = PriceEffect.NONE)

I tried using Option, but didn't seem to work.

**Comment by Graeme22** [comment]
The keys are still present for me, but looks like they're not guaranteed to be present! I'll make them optional. Thanks for identifying this!
