### ISSUE TITLE
Missing feature: Bracket Orders

### ISSUE THREAD

**Issue by Graeme22** [tastyware/tastytrade#63]
Currently the SDK doesn't support bracket orders as documented here: https://[developer.tastytrade.com/order-management/](https://developer.tastytrade.com/order-management/)

This is a feature I'd like to support at some point.

**Comment by kaidaniel82** [comment]
Hi, is it still possible to use the OTOCO order to implement a Bracket order? The example on the Tasty website shows this, right? It would be great if we could see an example of this.

**Comment by Graeme22** [comment]
Hi, this is still not implemented. If you'd like to create a PR to add it, feel welcome! It looks like it's a grouping of three orders: opening order, stop loss, and profit taking, all wrapped into one. The `ComplexOrder` class is a wrapper for one of these that's already placed, but in order to actually create one using the API you'd need to make a new class similar to `NewOrder` but with the `OTOCO` type and the relevant parts.

**Comment by Quenos** [comment]
Solved in PR #107

**Comment by kaidaniel82** [comment]
When will it be merged to main?

**Comment by Graeme22** [comment]
As soon as the tests are passing!

**Comment by Graeme22** [comment]
This can now be done pretty easily:

```python
symbol = Equity.get_equity(session, 'AAPL')
opening = symbol.build_leg(Decimal(1), OrderAction.BUY_TO_OPEN)
closing = symbol.build_leg(Decimal(1), OrderAction.SELL_TO_CLOSE)
otoco = NewComplexOrder(
    trigger_order=NewOrder(
        time_in_force=OrderTimeInForce.DAY,
        order_type=OrderType.LIMIT,
        legs=[opening],
        price=Decimal('180'),
        price_effect=PriceEffect.DEBIT
    ),
    orders=[
        NewOrder(
            time_in_force=OrderTimeInForce.GTC,
            order_type=OrderType.LIMIT,
            legs=[closing],
            price=Decimal('200'),  # take profits
            price_effect=PriceEffect.CREDIT
        ),
        NewOrder(
            time_in_force=OrderTimeInForce.GTC,
            order_type=OrderType.STOP,
            legs=[closing],
            stop_trigger=Decimal('160'),  # stop loss
            price_effect=PriceEffect.CREDIT
        )
    ]
)
resp = account.place_complex_order(session, otoco, dry_run=False)
```

For an OCO order, it's exactly the same, but without the `trigger_order`, and it only works for positions you already have open.

**Comment by kaidaniel82** [comment]
Thats great. Thanks for developing this.
