### ISSUE TITLE
Documentation help wanted!

### ISSUE THREAD

**Issue by Graeme22** [tastyware/tastytrade#68]
The current docs are nice, but they're pretty much just one big SDK reference, so anyone new to the project is going to have to hunt around a lot to figure out how to do anything.

What I'd like to have is a proper documentation section, apart from the auto-generated reference, that contains examples and explanations for the most common features, kind of like the current `README.rst` but more extensive.

Any help is welcome!

**Comment by cdsmith1963** [comment]
Hi Graeme, I just posted an issue tied to get_market_metrics(). I'm a neophyte when it comes to GitHub and writing cool documentation but I'd like to give it a try. How about I start with the metrics.py module? Any good links or videos I can take a look at to help write solid documentation and contributions?

**Comment by Graeme22** [comment]
That sounds great! For examples, you could look at the `docs/session.rst` file. Everything is ReSTructured text, so if you look that up you should find plenty of examples/tutorials. Thanks in advance for the contribution!
