### ISSUE TITLE
Unable to Instantiate Abstract Class ProductionSession

### ISSUE THREAD

**Issue by alexonab** [tastyware/tastytrade#74]
```
from tastytrade import ProductionSession

import os
from dotenv import load_dotenv

load_dotenv()

username = os.environ["TW_USERNAME"]
password = os.environ["TW_PASSWORD"]

session = ProductionSession(username, password)
```

` $ python tw.py `

>Traceback (most recent call last):
>  File "/tmp/tw/tw.py", line 11, in <module>
>    session = ProductionSession(username, password)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>TypeError: Can't instantiate abstract class ProductionSession with abstract methods base_url, headers, session_token, user

**Comment by Graeme22** [comment]
Can you post your code?

**Comment by alexonab** [comment]
@Graeme22 I have added the code above.

**Comment by Graeme22** [comment]
Hmmm... What's your python version?

**Comment by alexonab** [comment]
> Hmmm... What's your python version?

$ python
Python 3.11.4 (main, Jun  7 2023, 10:13:09) [GCC 12.2.0] on linux

**Comment by Mytak** [comment]
Reproduced with Python 3.10.6, Ubuntu 22.04. Code(working before update to V6.0):

from tastytrade import ProductionSession

class TastyTradeSession():
    def __init__(self, user):
        # Get credentials
        self.user = user
        self.password = keyring.get_password('Tastytrade', self.user)
        return
    
   # Get session
    def get_session(self):          
        return ProductionSession(self.user, self.password)

**Comment by Graeme22** [comment]
That's an ugly mistake by me! Sorry about that.

Basically, I had the package installed as an editable package and was testing in a Jupyter notebook, which prevented me from running into this. Fixing it right now!
