### ISSUE TITLE
Certification session Streamer creates error when trying to create

### ISSUE THREAD

**Issue by maneum1** [tastyware/tastytrade#79]
Hello, 
on the latest version 6.1 I just created certification session
Then when trying to create a streamer with that session I get the following error.
```
'CertificationSession' object has no attribute 'streamer_token'
```
Looking in the code (streamer.py) there is a hint on the streamer class, that a production session is required.

Can you clarify what can be done with a Cert Session and what not?

Thanks

**Comment by Graeme22** [comment]
Certification sessions can no longer be used to create a streamer as of the last API update. IMO they're not very useful because the capabilities are quite limited.

**Comment by maneum1** [comment]
Thanks for clarifying.
Does this only affect the market streamer or also the account streamer?
I would figure if you can place sim orders you want to be able to track the P/L in testing, for which the account streamer would be needed,

**Comment by Graeme22** [comment]
I believe just the market streamer, if you can't get the account streamer to work feel free to open a separate issue.
