### ISSUE TITLE
Suspicious Login msg from Tasty

### ISSUE THREAD

**Issue by leaph** [tastyware/tastytrade#8]
Hi,
is there any way to avoid the Suspicious Login Detected email from TastyTrade? It says "user agent of python-requests/[2.28.2]".
Changing the user agent name to the same as they use in the desktop software could be an option?

**Comment by Graeme22** [comment]
We certainly could change it, however my intention with the API isn't exactly to go "under the radar" so to speak. Once the first login is approved, the rest should work without incident. The same process happens all the time when e.g. you login for the first time on a new browser or from a new location. So I wouldn't view it as a problem to be resolved. Also as a side bonus tasty will be able to see the logins and hopefully provide us with an official API or officially support this one as they realize that there's demand for it.
