### ISSUE TITLE
Fetching Greeks via get_event() fails with "TypeError: tastytrade.dxfeed.greeks.Greeks() argument after ** must be a mapping, not list"

### ISSUE THREAD

**Issue by JBlohm** [tastyware/tastytrade#88]
**Describe the bug**
Playing around with code as per docs/sessions.rst (Fetching greeks example), I stumbled upon a TypeError.

TypeError: tastytrade.dxfeed.greeks.Greeks() argument after ** must be a mapping, not list

**How to reproduce**

    # Fetching greeks get_event demo
    chain = get_option_chain(session, 'SPLG')
    print(chain[date(2023, 10, 20)][0])
    streamer_subs_list = [chain[date(2023, 10, 20)][0].streamer_symbol]
    print('streamer_subs_list is: ',streamer_subs_list)
    greeks = session.get_event(EventType.GREEKS, streamer_subs_list)    # Fails here
    print(greeks)

**How to fix**

I have created a temporary fix for my local installation by changing the following code in tastytrade/session.py

    def _map_event(
    
    ....

    if event_type == EventType.GREEKS:
        return Greeks(**event_dict[0])                <---- Change here: event_dict changed to event_dict[0]
    elif event_type == EventType.PROFILE:
        return Profile(**event_dict)
    elif event_type == EventType.QUOTE:
        print('Debug-map-event:', event_dict)
        return Quote(**event_dict)
    elif event_type == EventType.SUMMARY:
        return Summary(**event_dict)
    elif event_type == EventType.THEO_PRICE:
        return TheoPrice(**event_dict)
    elif event_type == EventType.TRADE:
        return Trade(**event_dict)
    elif event_type == EventType.UNDERLYING:
        return Underlying(**event_dict[0])  # type: ignore
    else:
        raise TastytradeError(f'Unknown event type: {event_type}')

**Way forward**

As I am not 100% sure if the problem is actually on the receiving side in _map_event or on the sending side in greeks = session.get_event(EventType.GREEKS, streamer_subs_list) , please check once more if my suggested fix is the right way to do it.

**Comment by Graeme22** [comment]
Nice catch! Looks like the format for dxfeed `Profile` events has changed since I wrote the docs. Fixing shortly!
