### ISSUE TITLE
Transition to official TT API

### ISSUE THREAD

**Issue by Graeme22** [tastyware/tastytrade#9]
Now that TT has released their official API, it's a bit easier to implement the changes and no longer requires a reverse-engineering setup.

All of this project remains relevant and useful towards a Python implementation of the official API.

There's already another person out there making a Python implementation, I'm not sure if he's aware of this project but I reached out to him to see if we can collaborate since there's no need to start from scratch.

**Comment by MaxxRK** [comment]
Do you have a link to the official API I cannot seem to find it on their webpage

**Comment by Graeme22** [comment]
Yes! It's a bit buried. First you have to enable it on the main page, log in then go to My Profile > Developer.

From there you can log in at developer.tastytade.com

**Comment by Graeme22** [comment]
Closing as the transition is underway!
