### ISSUE TITLE
Urgent: Classic streamer moved to delayed quotes

### ISSUE THREAD

**Issue by Graeme22** [tastyware/tastytrade#95]
Here are the contents of the email sent to the TT API customers:

> We trust you are having a positive experience with the tastytrade Open API. We are reaching out to inform you that we are upgrading and provisioning dedicated streaming market data capacity for Open API consumers, which will require a code update to your application. We have updated the Streaming Market Data section of our documentation here: https://developer.tastytrade.com/streaming-market-data/ with relevant details about the new dxLink protocol and with the new endpoints.
> 
> For a short transitional period, the market data available on the Open API multiplexors will be limited to US-listed equities, SMALL exchange futures, and cryptocurrency. We are working diligently to add US-listed equity options, CFE and CME futures.
> 
> We are requiring customers to read the updated documentation and make the necessary updates to their applications to transition to these new multiplexors within the next 48 business hours. After 48 business hours, any accounts still using the old multiplexors will be moved to delayed quotes until they make the necessary updates. This will impact both your API and platform market data. We recognize the inconvenience of this change and temporary limited data offering, but in the long run this will present a better experience for Open API customers.

The overall effect of this is to make the streamer pretty much useless. So #83 is now top priority, as we need to transition to the new streamer ASAP.

**Comment by michaelcooke** [comment]
This is likely tastytrade delaying your data arbitrarily. Realtime data via dxFeed QDS is still up. See https://github.com/tastyware/tastytrade/pull/83#issuecomment-1783035502
