### ISSUE TITLE
session.get_candle() problem if market closed

### ISSUE THREAD

**Issue by kaidaniel82** [tastyware/tastytrade#96]
The response status is 200 but, as expected, no data point is available. This causes the code in line 233 in the session.py to crash.

start_day = WEEKEND
session.get_candle(symbols=['VIXY'], interval='5m', start_time=start_day)    

leads to:
KeyError: <EventType.CANDLE: 'Candle'>

**Comment by Graeme22** [comment]
Can you add more context? E.g. what date is `WEEKEND`?

**Comment by kaidaniel82** [comment]
It appears to be an edge case. The data from yesterday didn't work yesterday but is functioning today. The data from today isn't working at the moment. Regardless, if **data = response.json()[EventType.CANDLE]** in **session.py** line 233 doesn't contain candle data, the code crashes. This could be easily fixed by validating whether the key exists in the response **dict()**.
 

from datetime import datetime, timezone
from tastytrade import ProductionSession

session = ProductionSession('USER', 'PW')
start_day = datetime(2023, 11, 12, tzinfo=timezone.utc) # THIS is TODAY

print(start_day)
data_history = session.get_candle(symbols=["VIXY"], interval="5m", start_time=start_day, end_time=None)

**Comment by Graeme22** [comment]
Ah, makes sense now. So the market is closed weekends, the data you're trying to fetch doesn't exist.

I'm going to close this, your fix would prevent the crash but since this is incorrect usage I think the error is appropriate.

**Comment by kaidaniel82** [comment]
I would agree if the behavior was consistent. Yesterday's date works today, but not yesterday. If I set extendet tradfing hours to True, the date no longer works. There are some combinations that work but not 100%.

**Comment by Graeme22** [comment]
Yesterday's date was also invalid though.

Since this is an SDK, it's not unexpected that an error would be thrown by illegal/nonsensical requests. If you for some reason need to cover those cases, you can use error handling in your application.
